name: ${name}
version: ${version}
description: ${description}
authors: [Gecolay]
website: https://www.spigotmc.org/resources/62325
main: ${main}
api-version: 1.16
folia-supported: true
softdepend: [GriefPrevention, PlaceholderAPI, PlotSquared, WorldGuard]

commands:

  gsit:

    usage: /<command> [toggle|playertoggle]
    aliases: [sit]
    description: Sit command

  glay:

    usage: /<command>
    aliases: [lay]
    description: Lay command
    permission: GSit.Lay

  gbellyflop:

    usage: /<command>
    aliases: [bellyflop]
    description: BellyFlop command
    permission: GSit.BellyFlop

  gspin:

    usage: /<command>
    aliases: [spin]
    description: Spin command
    permission: GSit.Spin

  gcrawl:

    usage: /<command> [toggle]
    aliases: [crawl]
    description: Crawl command

  gsitreload:

    usage: /<command>
    aliases: [gsitrl]
    description: Plugin reload command
    permission: GSit.Reload



permissions:

  GSit.*:
    default: op
    description: GSit | Permissions
    children:
      GSit.Sit.*: true
      GSit.PlayerSit.*: true
      GSit.Pose.*: true
      GSit.Crawl.*: true
      GSit.Kick.*: true
      GSit.ByPass.*: true
      GSit.Update: true
      GSit.Reload: true

  GSit.Sit.*:
    default: op
    description: Sit | Permissions
    children:
      GSit.Sit: true
      GSit.SitClick: true
      GSit.SitToggle: true

  GSit.Sit:
    default: true
    description: Sit command | Permission

  GSit.SitClick:
    default: true
    description: Sit click | Permission

  GSit.SitToggle:
    default: true
    description: Toggle Sit ability | Permission

  GSit.PlayerSit.*:
    default: op
    description: PlayerSit | Permissions
    children:
      GSit.PlayerSit: true
      GSit.PlayerSitToggle: true

  GSit.PlayerSit:
    default: true
    description: PlayerSit click | Permission

  GSit.PlayerSitToggle:
    default: true
    description: Toggle PlayerSit ability | Permission

  GSit.Pose.*:
    default: op
    description: Pose | Permissions
    children:
      GSit.Lay: true
      GSit.BellyFlop: true
      GSit.Spin: true

  GSit.Lay:
    default: true
    description: Lay command | Permission

  GSit.BellyFlop:
    default: true
    description: BellyFlop command | Permission

  GSit.Spin:
    default: true
    description: Spin command | Permission

  GSit.Crawl.*:
    default: op
    description: Crawl | Permissions
    children:
      GSit.Crawl: true
      GSit.CrawlSneak: true
      GSit.CrawlToggle: true

  GSit.Crawl:
    default: true
    description: Crawl command | Permission

  GSit.CrawlSneak:
    default: true
    description: Crawl sneak | Permission

  GSit.CrawlToggle:
    default: true
    description: Toggle Crawl ability | Permission

  GSit.Kick.*:
    default: op
    description: Kick | Permissions
    children:
      GSit.Kick.Sit: true
      GSit.Kick.Pose: true

  GSit.Kick.Sit:
    default: op
    description: Kick sit | Permission

  GSit.Kick.Pose:
    default: op
    description: Kick pose | Permission

  GSit.ByPass.*:
    default: op
    description: ByPass | Permissions
    children:
      GSit.ByPass.World: true
      GSit.ByPass.Region: true

  GSit.ByPass.World:
    default: op
    description: ByPass world | Permission

  GSit.ByPass.Region:
    default: op
    description: ByPass region | Permission

  GSit.Update:
    default: op
    description: Update notification | Permission

  GSit.Reload:
    default: op
    description: Plugin reload command | Permission