name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Build and package Gradle project
        run: ./gradlew build

      - name: Upload to release
        uses: cloudnode-pro/release-upload-asset@1.0.2
        with:
          gh-token: ${{ github.token }}
          files: build/libs/GSit-${{ github.event.release.tag_name }}.jar; type=application/java-archive

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@2.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ github.event.repository.custom_properties.modrinth_id }}
          name: ${{ github.event.release.name == github.event.release.tag_name && format('GSit {0}', github.event.release.name) || github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: |-
            paper
            folia
            purpur
            spigot
            bukkit
          game-versions: |-
            1.16.x
            1.17.x
            1.18.x
            1.19.x
            1.20.x
            1.21.x
          files: build/libs/GSit-${{ github.event.release.tag_name }}.jar
